### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by Mario25402** [eigenric/bibliofetch#7]
¡Hola!, te abro el issue para debatir que lenguaje de programación vamos a usar en el desarrollo de tu proyecto.

**Comment by eigenric** [comment]
Saludos @Mario25402 . Había pensado que Go puede ser una buena elección. Es un lenguaje de programación compilado que busca combinar la eficiencia de lenguajes como C con la simplicidad de los lenguajes de scripting, como Python. Además de haber dado buenos resultados anteriores en la asignatura ¿Qué te parece?

**Comment by Mario25402** [comment]
Me parece un lenguaje adecuado, por mi parte bien.
